### ISSUE TITLE
Create a definition file for the Github exporter

### ISSUE THREAD

**Issue by gsanchezgavier** [newrelic/nr-integration-definitions#17]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

Create a definition file for the [Github exporter]( https://github.com/infinityworks/github-exporter
)

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

## Desired Behavior

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Possible Solution

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by paologallinaharbur** [comment]
It is the https://github.com/infinityworks/github-exporter missing

**Comment by gsanchezgavier** [comment]
fixed in #18
